---

clusternet:
    type: shell
    exec: "/usr/bin/env node /vccjs/clusternet.js"

clusterdns:
    type: daemon
    node: yes
    exec: "/vccjs/clusterdns.js"
    requires: clusternet

loadtargets:
    type: module
    module: "/vccjs/loadtargets.js"
    class: LoadTargets
    requires: clusterdns

wait4deps:
    type: shell
    exec: "/usr/bin/env node /vccjs/wait4deps.js"
    requires: loadtargets
    provides: clusterstart

registerservice:
    type: daemon
    node: yes
    exec: "/vccjs/registerservice.js"
    requires: clustertargets

clusterwatcher:
    type: daemon
    node: yes
    exec: "/vccjs/clusterwatcher.js"
    requires: clustertargets